// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCTSWg1isO7d_zgSKeMTwIjB8NSp_gBU0o',
    appId: '1:835667889247:web:6d86da70f314e33dea9fea',
    messagingSenderId: '835667889247',
    projectId: 'valetflowqr-40544',
    authDomain: 'valetflowqr-40544.firebaseapp.com',
    storageBucket: 'valetflowqr-40544.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCv5WWegWn2B9hVTKJfD68KDrNDvSwOHjI',
    appId: '1:835667889247:android:0e52413c71639ccbea9fea',
    messagingSenderId: '835667889247',
    projectId: 'valetflowqr-40544',
    storageBucket: 'valetflowqr-40544.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAVekZTEu8rjLLaOaq3MvYZgNo60TXiEn4',
    appId: '1:835667889247:ios:43a058e6c0949ed0ea9fea',
    messagingSenderId: '835667889247',
    projectId: 'valetflowqr-40544',
    storageBucket: 'valetflowqr-40544.firebasestorage.app',
    iosBundleId: 'com.example.valetPwa',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAVekZTEu8rjLLaOaq3MvYZgNo60TXiEn4',
    appId: '1:835667889247:ios:43a058e6c0949ed0ea9fea',
    messagingSenderId: '835667889247',
    projectId: 'valetflowqr-40544',
    storageBucket: 'valetflowqr-40544.firebasestorage.app',
    iosBundleId: 'com.example.valetPwa',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCTSWg1isO7d_zgSKeMTwIjB8NSp_gBU0o',
    appId: '1:835667889247:web:01917e0e11c749abea9fea',
    messagingSenderId: '835667889247',
    projectId: 'valetflowqr-40544',
    authDomain: 'valetflowqr-40544.firebaseapp.com',
    storageBucket: 'valetflowqr-40544.firebasestorage.app',
  );

}