// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDMvLinoPtsoXsoQgIC8M8eosPJQu6o79s',
    appId: '1:834741301798:web:0b9928af2d6ff1a3252ce7',
    messagingSenderId: '834741301798',
    projectId: 'valetflowqr',
    authDomain: 'valetflowqr.firebaseapp.com',
    storageBucket: 'valetflowqr.firebasestorage.app',
    measurementId: 'G-NNH3R0CW8K',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDZCOmQWbKcbuoyk6czcgtsAcWAqQL8Q70',
    appId: '1:834741301798:android:28b573a31340364c252ce7',
    messagingSenderId: '834741301798',
    projectId: 'valetflowqr',
    storageBucket: 'valetflowqr.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC_s1ThuW8BQCoDKJmN_r9FMk_UlniBMck',
    appId: '1:834741301798:ios:0bba63cde4651cfa252ce7',
    messagingSenderId: '834741301798',
    projectId: 'valetflowqr',
    storageBucket: 'valetflowqr.firebasestorage.app',
    iosBundleId: 'com.example.valetPwa',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC_s1ThuW8BQCoDKJmN_r9FMk_UlniBMck',
    appId: '1:834741301798:ios:0bba63cde4651cfa252ce7',
    messagingSenderId: '834741301798',
    projectId: 'valetflowqr',
    storageBucket: 'valetflowqr.firebasestorage.app',
    iosBundleId: 'com.example.valetPwa',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDMvLinoPtsoXsoQgIC8M8eosPJQu6o79s',
    appId: '1:834741301798:web:2d7eae535738aa78252ce7',
    messagingSenderId: '834741301798',
    projectId: 'valetflowqr',
    authDomain: 'valetflowqr.firebaseapp.com',
    storageBucket: 'valetflowqr.firebasestorage.app',
    measurementId: 'G-F9471N1XSX',
  );
}
