name: valet_pwa
description: "PWA para cliente"
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.9.0


dependencies:
  flutter:
    sdk: flutter
  shared:
    path: ../../shared


  cupertino_icons: ^1.0.8
  firebase_core: ^3.15.2

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^5.0.0


flutter:


  uses-material-design: true

