name: shared_models
description: "Modelos de datos compartidos para todas las apps"
version: 0.0.1
publish_to: "none"

environment:
  sdk: ">=2.17.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
