name: shared
description: Código compartido entre las apps del monorepo
version: 0.0.1
publish_to: none

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  cloud_firestore: ^5.4.4
  firebase_auth: ^5.3.1
  firebase_core: ^3.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter
